IMPLICIT_WAIT = 5
EXPLICIT_WAIT = 4
WINDOW_SIZE = ('1280', '1024')
BASE_URL = 'http://selenium1py.pythonanywhere.com/'
PRODUCT_URL = 'http://selenium1py.pythonanywhere.com/en-gb/catalogue/coders-at-work_207/'
LOGIN_URL = 'http://selenium1py.pythonanywhere.com/en-gb/accounts/login/'
EMAIL_LOGIN = 'Test_Email_2020-07-22_19-56-45@gmail.com'
PASSWORD = "test@test"
FIRST_NAME = 'Gurbanguly'
LAST_NAME = 'Berdimuhamedow'
ADDRESS = 'Kolola Pushta Rd.'
CITY = 'Kabul'
ZIP_CODE = '1001'
COUNTRY = 'Afghanistan'